spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
